### ISSUE TITLE
Data Points - NYC zip codes (PLEASE IGNORE - PROBLEM SOLVED)

### ISSUE THREAD

**Issue by ericalucia** [jueyang/call-me-maybe#11]
Hello Jue,
I am still unsure of how to get the data points for the H.S. student zip codes. I put both the lat/long and addresses in this updates csv file. Can you help me find out how to actually map the data points? I think I either need a walk through on CartoDB or the query.

https://gist.github.com/ericalucia/3c88d576eb9daab93cff

**Comment by jueyang** [comment]
Cool. I'll get back to you tonight!

**Comment by jueyang** [comment]
@ericalucia 

File looks good, except it looks like a tsv (tab-seperate value) rather than a csv (comma-separated file.) All you need to do is to change the file name to `dalton-hs-zipcode.tsv` (Not using space in filenames is a good practice.) You could either upload your local file up to CartoDB, or just use the gist url.

If you use the gist url, click the `raw` button on your gist after you change the file name, and paste that url to create a CartoDB table.

Now just one step away from making points! You will probably notice a column called `the_geom` in your table once you created it. That is your dot on the map. You have this column because you already include latitude and longitude in the data. 

See, CartoDB is smart! I looked at the file and for some reason a few rows didn't get a value. So the better thing to do here is to geocode the table again with CartoDB's geocoder. To do that:
- click `the_geom` column
- choose `geocode by address` in the prompt window
- the geocoder will run, and populate `the_geom` column with the new coordinates

Now go to "Map View". See the points? 

In the next comment I will add things about selecting the zipcode.

**Comment by jueyang** [comment]
@ericalucia LOL just noticed your capped title. Gotcha. I'll close this issue :)

**Comment by ericalucia** [comment]
Jue,
To be honest I'm still not sure how I got to the point I did, but I have a
map now.

**Comment by jueyang** [comment]
@ericalucia I'll post some fill-in-the-gap links to the class issue queue. CartoDB has pretty good docs. Hopefully that would answer some questions :)

**Comment by ericalucia** [comment]
Thank you Jue!
