### ISSUE TITLE
How do I create a data visualization story for Broadcast Craft

### ISSUE THREAD

**Issue by naeisharose** [jueyang/call-me-maybe#12]
I'm not exactly sure how to approach this story for broadcast using data visualization, my deadline is March 9th. I'm pitching my story for tonight at 10 pm.

I'm not sure which story would work as both a data visualization and broadcast story, but here are some story ideas I plan to use. 

1) More Americans are pushing off retirement. As a result those that are over 70 1/2 years have to readjust how the contribute and receive distributions from their IRA, qualified plans, profit sharing plans, Roth IRAs, and 401ks. 

2) Recently, there has been a study done that 1.1 billion young adults and teens are at risk of permanent hearing loss because of earbuds.

3) On Gwyneth Paltrow's lifestyle website, Goop, she made claims that there is an organ that the general population does not know about and its called fascia, which is essential to many of our health needs. Some of her claims can't be proven, however, many health professionals say that she is partially true about the benefits of fascia being ignored for years. It has a relationship to our body's pain, motion and flexibility. Fascia is a connective tissue that surrounds organs, bones, muscles, nerves, and tendons.

**Comment by naeisharose** [comment]
Sorry tonight at 8pm.

**Comment by jueyang** [comment]
Thanks for the question! My advice would be to go with either 1

**Comment by jueyang** [comment]
Thanks for the question, @naeisharose! My advice would be to go with either 1 or 2. No.3 could be interesting if you had source that could support/debunk the myth... It might take a lot of qualitative digging rather than patterns driven from large amounts of data.
- **For no.1**: With some investigation, you can get multiple datasets regarding IRA & retirement. Census probably already has useful information. This is potentially interesting because you will be explaining a fairly nuanced social-economic phenomenon.
- **For no.2**: Sounds like you can at least start with the study that made the claim. You can get the data that they used and add more to it. Your story could potentially be linked to the music consumption behavior and the role of technology (such as itune usage/spotify subscribers, etc.) 

How much time do you have for this project?

**Comment by jueyang** [comment]
Also let me know what tools you are comfortable using, this will help me understand the scope of your project better. Thx!

**Comment by naeisharose** [comment]
Well i'm not sure how exactly one would tie data-vis together with
broadcast. So that's another thing that I'm trying to figure out
storytelling wise.

**Comment by jueyang** [comment]
One example I can think of is this: http://www.vox.com/a/barack-obama-interview-vox-conversation/obama-interview-video

**Comment by jueyang** [comment]
When you say broadcast it's a pretty broad term (no pun intended,) can you expand the broadcasting aspect? A few things to consider:
1. Would you be pointing to an already made graphic of some sort?
2. Would you do a post-production of laying the data over such as in the Vox video?
3. Would there be any audience interaction?

**Comment by jueyang** [comment]
The scope + time questions still remain... It will shape the direction of your project. I have some time to chat in the next 30 minutes if you want to stop by.

**Comment by naeisharose** [comment]
Hmm. I would definitely need help on doing the animation for this.

**Comment by naeisharose** [comment]
Yes, definitely. Where is your office?

**Comment by jueyang** [comment]
Well, that is a very high-production project... Have you taken a data viz class or any other coding classes here?

**Comment by jueyang** [comment]
I'll invite you via slack. What's your email?

**Comment by naeisharose** [comment]
naeisha.rose@journalism.cuny.edu

I've taken HTML with Hickman, I did the data scraping over the January
Academy but I don't think I have any of those scraping notes on hand with
me.

That's about it.

**Comment by naeisharose** [comment]
I think the piece is going to be 2 minutes and 30 seconds.

**Comment by jueyang** [comment]
K look out for the slack invite.
