### ISSUE TITLE
Doing a salary poll or survey - best tools?

### ISSUE THREAD

**Issue by JuliaJRH** [jueyang/call-me-maybe#18]
Hi Jue! 👋

I'm a student in the social-j program, and I have an idea but I'm not sure the best way to execute it. And I'm not sure if it's something I should try to do on my own now (I'd like to, I'm impatient), or wait until our class in the summer. 

**Here's the problem I'm trying to solve:** I'm supposed to be finding out the income distribution of my people on my beat. My beat is newsroom social media editors. There's not a lot of publicly available data about it. It's also a pretty small population size, all things considered. 

**Here's the secondary problem I'm trying to solve:** Other people (read: those in my community) are curious about how much other social media editors are making. And like lots of people have written about lately, one of the best ways to close the gender pay gap is for everyone to talk about how much you make (knowledge = power 💪). But there's no super-easy way for people to talk about this sensitive issue on a large scale. 

**Here's my initial idea:** I'd like to develop a poll/survey (what's the difference?) that I can send to specific sources I've talked to and that they can send to their work friends. The poll would ask:
- job title, 
- salary, 
- how many years of experience you had when you started receiving that salary,
- some kind of geographical/market size/cost-of-living question

Then after I get enough responses (how many is enough?), I'll develop a way to share that information back to the community, which will provide them a benefit, and hopefully encourage others to share their salaries. It could be as simple as me doing a little averaging and posting the average salary for people with x years of experience. Or it could be something interactive, where after you put in your information, it immediately is able to tell you where you stand compared with others with your experience level, or your geography, or whatever parameters you choose. However, I feel like I can't get that up and running until I have a good base chunk of data. 
## So...

_Should I just go ahead and write a survey in Google Forms or something, post it and start collecting data, figuring out exactly what I want to do with it later?_
_Or should I wait until after the summer semester starts and we flesh out the idea more?_
_Is there a better tool than Google Forms?_

**Comment by jueyang** [comment]
Hey Julia, thanks for walking me through your thought process. I have some suggestions based on what you said here.

First, :+1: for having a clear idea of your users and goals:

> finding out the income distribution of newsroom social media editor, a pretty small population size

And it's great that you have identified a problem:

> there's no super-easy way for people to talk about this sensitive issue on a large scale. 

## Main thread + questions

The main thread I see from your process is this: **social media editors are not talking/have no ways to talk about their salaries. Information is not transparent.**

So here are some questions for you:
1. What kind of change would you like to see by providing people a way of talking about salary? What's the **higher goal** beyond just starting a conversation?
2. What do you mean by large scale? How do you measure the scale?
3. How to facilitate a conversation that could push the agenda while protecting people’s privacy? What’s the benefit of being totally/partially transparent?
4. What's particular about your community? Since they are all social media editors, are they more likely to be on top of their social media as the main way of consuming information?
5. Is there any implication of your higher goal to other communities in the newsrooms and/or other industries?

## First steps

> I'd like to develop a poll/survey (what's the difference?) that I can send to specific sources I've talked to and that they can send to their work friends. Then after I get enough responses (how many is enough?), I'll develop a way to share that information back to the community, which will provide them a benefit, and hopefully encourage others to share their salaries. 

Good idea! I would think the first step of what you are doing is closer to a survey. (If you are interesting to learning the difference between poll and survey, [this](http://en.wikipedia.org/wiki/Opinion_poll) and [this](http://en.wikipedia.org/wiki/Survey_methodology) wikipedia page help :)

This survey doesn’t have to be comprehensive. It doesn't even have to be distributed among the biggest audience. But -- 

It needs to be clear on what point you would like to make with each question. Elaborate the geographical/market size/cost-of-living a bit more. Do you aim to get first-person account for this? Or is this something you could get from elsewhere?

Unloading some data to third party datasets might have a few benefits, namely:
1. You are using a consistent measure across all participants, thus ruling out biases (say cost of living for a single person and a young family would be pretty different.
2. You make life easier for those who choose to answer the survey. 

## Next steps

> Or it could be something interactive, where after you put in your information, it immediately is able to tell you where you stand compared with others with your experience level, or your geography, or whatever parameters you choose.

Great. You don’t have to have a huge chunk of data to make that happen. Make it clear to your participants how many other people to which they are compared.

> Should I just go ahead and write a survey in Google Forms or something, post it and start collecting data, figuring out exactly what I want to do with it later?*

Yes. Get a group of participants to answer questions you think will demonstrate a point. Google form is easy to create, manage and distribute. So use it.

**Comment by jueyang** [comment]
Also. See what has been done. 
- Buzzfeed simple survey. Read the asterisk. http://www.buzzfeed.com/jtes/heres-what-female-and-male-journalists-actually-make#.uiPq3B1Od
- Glassdoor anecdote. http://www.glassdoor.com/Salaries/social-media-editor-salary-SRCH_KO0,19.htm

**Comment by jueyang** [comment]
Enjoyed your presentation! Looking forward to your idea blurb.
