### ISSUE TITLE
Summer project

### ISSUE THREAD

**Issue by cristinafurlong** [jueyang/call-me-maybe#20]
Hi Jue, 
Here is part of a project I want to work on this summer. Mapping schools, after school programs, UPK seats, including private schools. Putting in enrollment numbers, crossing guards...and then collision data from NYPD. 
2nd stage would be making a channel for complaints and requests to the appropriate agency, DOE, DOT or NYPD. It doesn't exist. I've talked to about three council members who will be pushing for DOE to play a role in Vision Zero this year. 
Sadly, I input the schools data by hand, as I couldn't figure out how in the time I had. 
NOTE; It is so difficult to get real counts of school kids. UPK isn't included in schools lists, though UPK is free and full day now.Also, after school programs have tons of kids...
http://bit.ly/1EbpavR

**Comment by jueyang** [comment]
Hey @cristinafurlong,

These are all great prospects, and thank you for elaborating more at your presentation :) Here're some thoughts for you.

### Need a smaller scope

For the summer specifically, I suggest focusing on one aspect of what you listed. The current scope which you listed above is too big for 11 weeks. If you can focus on one problem and one problem only, you will be able to get further than trying to solving all the problems at once.

### How would you use the data (if that's what you're looking for)

As you might be aware already, data gathering itself is a big task. Depending on the available sources, completeness level of exiting dataset, and your/your organization's time, you might get partial, incomplete data, or might need to collect them by visiting multiple offices, calling multiple agencies (and very possibility entering some by yourself.) Your product for the summer, therefore, could be a dataset that Vision Zero (or other advocacy orgs) can use in the future. Let me ask:

**How would your community benefit from a perfect dataset?** Is it new awareness of the lack of pedestrian safety? Ways to contact local officials with hard numbers as evidence? Ways to organize and advocate amongst themselves? and

**What work needs to be done on top of the dataset itself?** For example, data analysis, visualization, etc?

### Take a step back

I'd like to hear more about the higher level thoughts you have in terms of using the data (which, in turn, shapes what is necessary to collect, or not.) But before that, let's take a step back. Datasets are great. They give your advocacy group evidence to influence policy. But what if the process of collecting them/opening them up is broken? Could that actually be more valuable to tackle?

For example, as you mentioned, it is really difficult to get the actual counts of school kids. That seems to me a concrete problem -- if you can't have an accurate count of enrollment, the policy implication that depends on those numbers can easily vary. Maybe it's worth to think of your product as **a service to get correct enrollment numbers from schools** or something along the lines. 

### In sum, clarify who your users are

If you are looking at completing a dataset, your users are advocacy groups, because they are turning the numbers into something meaningful. If you are figuring out a way to improve the dataset, you are looking at direct end users being schools, advocacy orgs, or parents.

As Jeff said during the presentation, think about where you'd like the impact to be, and that will help shape your product.

Looking forward to receiving your idea pitch on Slack. Let me know if you have other questions!
