### ISSUE TITLE
Product Development Studio

### ISSUE THREAD

**Issue by RoshanA** [jueyang/call-me-maybe#22]
Hi Jue - We met a few months ago to speak about building a curriculum at the j-school, where I'm starting in the Fall.. I noticed that you are teaching a product development studio (I think for the social j program?) this summer and I was wondering if it would be possible for me to sit in on a class. Please let me know. Thanks!

**Comment by jueyang** [comment]
Hey Roshan,

Since it's a studio class, the materials are individualized for each student. I work with everyone in the program to scope out a concrete product, for the respective community they work with. The dozen or so products will be built by our class developer and me. The students will be responsible for the UX research and product management.

It might be hard to "sit in" in a studio. That said, we have a couple of lecture/guest speaker sessions, mostly in the form of short presentations + longer Q&A. You are welcome to join those. We are not going to cover anything theoretical; rather, we discuss the current practice in product development.

The first session will be tomorrow (June 9th), starting from 1pm. Our developer and a guest designer will present a few projects and their processes. You could sit in on this one, and decide whether the class would be relevant to you.

Let me know if you plan to come.

**Comment by RoshanA** [comment]
Hi Jue - Thanks for your response. My interest in the class is mainly to see other peoples' projects and get a better idea of what kind of projects I could focus on over the summer and what kind of skills I should focus on learning now and in the fall. Sitting in on a guest presentation would be great, any day that you have student presentations or a student showcase would also be great. Please let me know the next time anything along those lines is taking place and it's okay to visit. Thanks much.

**Comment by jueyang** [comment]
Hey Roshan,

Could you leave you email here? I'd like to invite you to our class Slack channel. It is where we centralize all the class announcements and materials. Thanks.

**Comment by RoshanA** [comment]
Hi - My e-mail is Roshan.Abraham@gmail.com 

Thanks!
