### ISSUE TITLE
You said something about fast maps... tell me more

### ISSUE THREAD

**Issue by jueyang** [jueyang/call-me-maybe#3]
@raiCUNY DO IT

**Comment by RaiCUNY** [comment]
Hi Jue,

Can you tell me how to make a map, tracing the boutiques coming up in the gentrified neighborhood of Bushwick, Brooklyn. I would like to use a map to trace the difference in the price of a pair of jeans as we move through the neighborhoods and actually show how the price goes up when we go to a gentrified neighborhood because of the kind of people who have moved in.

**Comment by jueyang** [comment]
Thanks for reaching out! Great chatting with you as it helps me to understand your deadlines and skills right now. I pointed you to http://geojson.io for simple + fast data collection. Have fun adding data points and save them as a gist.

Glad to hear you are taking the html/css/js class :) You'll be closer to "what map? piece of :cake:! " at the end of this class.
