### ISSUE TITLE
Help on CSS 

### ISSUE THREAD

**Issue by mmelton3** [jueyang/call-me-maybe#8]
I made a page but it's not styling properly. I used a bootstrap template and soundcite clips but none of the css is showing up.

**Comment by jueyang** [comment]
Could you paste the code of your page in a gist? Thanks.

**Comment by mmelton3** [comment]
I did make the gist but It's not saving...

**Comment by jueyang** [comment]
Did you click the "Create secret Gist" (or public, whichever you'd like) Button?

**Comment by mmelton3** [comment]
I made a public one today.

**Comment by jueyang** [comment]
Great. Can you put the link here?

**Comment by mmelton3** [comment]
https://gist.github.com/mmelton3/ecf0cc2bf31b8b187178

**Comment by jueyang** [comment]
OK. A few things:
1. It's an html file, could you name it `somethingsomething.html`? That's how you would see the color coded syntax for html. Just go back to the gist, click on Edit on the top-right, and change the name.
2. You mentioned the css not working. It seems that you have one `<link>` to the `player.css` **outside** of the `<html>` tag, which is not a correct structure to link to css. Notice where you place your `bootstrap.css`? That's where you should put your css files.

**Comment by mmelton3** [comment]
With the player tag outside of the html, the clips will still play so they are working. And I added the codes for the player to what was already on the bootstrap template, I'm not sure which part of the code corresponds to the CSS. Also I tried adding the code from the page directly into the bootstrap CSS and the players stopped working.

**Comment by jueyang** [comment]
@mmelton3 You changed the description, instead of the file name.

Please remember the correct order for linking to stylesheets and js scripts is the first step to not introduce bugs to your webpage. I forked your gist, moved the `link` and `script` of soundcite to where they belong.

Please see what I changed. : https://gist.github.com/jueyang/f57a08497e90a6242b86/revisions

**Comment by mmelton3** [comment]
https://gist.github.com/mmelton3/ecf0cc2bf31b8b187178

I moved the audio player code from the top of the page, but that's not
really the issue...It's just missing the style.
and I'm not familiar with using github so I didn't know how to change the
title

On Thu, Feb 19, 2015 at 2:03 PM, Jue Yang notifications@github.com wrote:

> OK. A few things:
> 1. It's an html file, could you name it somethingsomething.html?
>    That's how you would see the color coded syntax for html. Just go back to
>    the gist, click on Edit on the top-right, and change the name.
> 2. You mentioned the css not working. It seems that you have one <link>
>    to the player.css _outside_ of the <html> tag, which is not a correct
>    structure to link to css. Notice where you place your bootstrap.css?
>    That's where you should put your css files.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jueyang/call-me-maybe/issues/8#issuecomment-75114192.

## 

*Monica Melton *
Freelance Master's Candidate
CUNY Graduate School of Journalism
(253) 590-9184
NYC News Service

**Comment by jueyang** [comment]
@mmelton3 please see my comment above https://github.com/jueyang/call-me-maybe/issues/8#issuecomment-75114192

**Comment by jueyang** [comment]
(accidental close, reopening)

**Comment by mmelton3** [comment]
Hey, I'm just now seeing this.
I think I'm just going to try and
rebuild the page from scratch at this point. 
of just use Wordpress.

**Comment by jueyang** [comment]
@mmelton3 You don't have to build the page from scratch because it's already there! Your current page looks like it just needs to link properly to the css. Is `bootstrap.css` in the `css` folder? Do you have the right webpage structure?

This is what you page looks like right now without the css: http://bl.ocks.org/jueyang/raw/f57a08497e90a6242b86/

**Comment by mmelton3** [comment]
I don't believe there's a CSS folder at all. I downloaded a bootstap CSS
template and put my code in it. But when I did the audio no longer worked.

I've moved things over to my wordpress site. This works for now but I will
need to know how to integrate the CSS for future projects.

Monica

On Sat, Feb 21, 2015 at 4:36 PM, Jue Yang notifications@github.com wrote:

> @mmelton3 https://github.com/mmelton3 You don't have to build the page
> from scratch because it's already there! Your current page looks like it
> just needs to link properly to the css. Is bootstrap.css in the css
> folder? Do you have the right webpage scaffold?
> 
> This is what you page looks like right now without the css:
> http://bl.ocks.org/jueyang/raw/f57a08497e90a6242b86/
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jueyang/call-me-maybe/issues/8#issuecomment-75394205.

## 

*Monica Melton *
Freelance Master's Candidate
CUNY Graduate School of Journalism
(253) 590-9184
NYC News Service

**Comment by jueyang** [comment]
Yes. Let's use this as a case study for the kind of things you'd like to
do. Depending on where your content lives, the css lives in different
places. In your webpage code it points to `css/bootstrap.css`, which
assumes you have a css folder set up. Some times just downloading bootstrap
would not work; you need to find where to put that css file.

We can discuss this so that you have a general understanding of how these
all work together :) Can you leave your email? We can continue to
chat/schedule a meeting on Slack.
