### ISSUE TITLE
Google Sheets broke my quiz :(

### ISSUE THREAD

**Issue by catharob** [jueyang/call-me-maybe#9]
Hey Jue,

I'm trying to submit a quiz I made last semester as a clip for an internship application. But it was a jquery that used Google Sheets as the source of the quiz data, and Google updated Sheets and it broke my quiz. 

The quiz template came from here: https://github.com/motherjones/newsquiz
Here's what my broken quiz looks like now: http://digitalstorage.journalism.cuny.edu/catherine.roberts/public_html/fms/Roberts%20Quiz/index.html

I already tried migrating the data in my old spreadsheet over to a new one in the new Sheets. That didn't work. :(

I'm working on a different quiz template right now, just in case I can't get this figured out, but it would be nice to use the motherjones one if it's fixable, since it's really a very nice format, when it's working. 

What do you think??? Thanks you for your help!!!

Catherine

**Comment by jueyang** [comment]
Google update usually breaks the tool/projects that depend on their service. A good reason that (over-)reliance on Google will contribute to human doom :beers: 

I'll fiddle with this a bit and get back to you.

**Comment by jueyang** [comment]
@catharob It turns out I might have blamed google too soon this time. Thought they updated their Sheet API and broke the code, but it's actually working fine for me.

Make sure that you have the most up to date news quiz template. The best way to do this is actually use your most recent git knowledge! You can fork Mother Jone's newsquiz repo to your own account. Clone (a new terminology, but basically means getting it from GitHub to your local computer) it, and start from there.

Let me know if you need help with that process. I can meet on Monday.

**Comment by jueyang** [comment]
Glad you came by! Let me know if you got more questions.

![](http://media.giphy.com/media/vnnoqBjIrJ73y/giphy.gif)
